# Generated by Django 2.0.6 on 2018-10-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockbuster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('yearReleased', models.IntegerField()),
                ('ageAllowed', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
